### ISSUE TITLE
Misleading message for new release 1.1

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela.github.io#111]
https://kubevela.io/docs/v1.1/end-user/components/webservice/#specification

![image](https://user-images.githubusercontent.com/2805315/118625944-07c6a580-b7fd-11eb-96f1-1c2f67de3d6d.png)

Release 1.1 should not be the out-of-date release, right?

**Comment by sunny0826** [comment]
This is a problem, in theory `v1.1` should be the same content as `next`.

**Comment by wonderflow** [comment]
Do we have any we to change the notify message for releases that newer than the current release?

**Comment by sunny0826** [comment]
> Do we have any we to change the notify message for releases that newer than the current release?

No, we need to delete the `v1.1` version of the document, collaborate in the `next` new document, when the `v1.1` version is officially released, we start writing `v1.2` version of the document is, and then generate this `v1.1` version of the document.
In the directory structure, the `next` version corresponds to the document in `/docs`.

**Comment by zzxwill** [comment]
BTW, why don't we have 1.0.4 version docs?
