### ISSUE TITLE
Command copy is not friendly

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela.github.io#114]
On page https://kubevela.io/docs/quick-start#step-2-deploy-your-first-application, when copying the command and paste it in cli, it will show as below.

```
$ kubectl apply -f https://raw.githubusercontent.com/oam-dev/kubevela/master/docs/examples/vela-app.yaml
application.core.oam.dev/first-vela-app created
```

This is not as expected. Only the command should be copied.

**Comment by sunny0826** [comment]
这个需要在 Markdown 文件去掉 `$` 符号，copy 这个按钮只会复制 ``` ``` 内的内容

**Comment by yangsoon** [comment]
https://github.com/oam-dev/kubevela/pull/1661 will fix it

**Comment by zzxwill** [comment]
> [oam-dev/kubevela#1661](https://github.com/oam-dev/kubevela/pull/1661) will fix it

Great.
