### ISSUE TITLE
translate i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md

### ISSUE THREAD

**Issue by zhujun74** [kubevela/kubevela.github.io#49]
除翻译规则外，是否可以使用自动翻译软件修改呢？谢谢

**Comment by wonderflow** [comment]
使用自动翻译软件指的是什么意思？

**Comment by zhujun74** [comment]
EDGE浏览器提供网页自动翻译功能，但现在在KUBEVELA文档上似乎不起效了，如果自动翻译网页的话，那就是人工做审校了吧？

**Comment by cheimu** [comment]
本质目的是提供一份中文文档。如果机翻可以做到让大家读完能轻松看懂在说什么 而不是不通顺 不知所云或者逻辑不通 那使用机翻来辅助没有什么问题。 但机翻普遍存在的问题就是 根本看不懂他在说什么 指代不明 逻辑不通 各种神奇的用词 都是目前机翻存在的问题。。。

**Comment by zhujun74** [comment]
确实机翻的还不尽人意，需要人员在一些词汇，术语上做修正。但还是解决了许多基础性的文档翻译事务性工作的，领域内人员基本可以理解，上出版物和正规注释就不行了。
